### ISSUE TITLE
feat: 최근 검색어 저장 및 조회 API

### ISSUE THREAD

**Issue by jaejunlee11** [seoul-night/bamgang-server#79]
### 작업 개요
- 최근 검색어 저장 및 조회 API구현

### 작업 내용
- 검색 시 해당 검색어 DB에 저장
- 최근 검색어 요청시 DB에서 최근 검색어 3개 전달

### Todo list
- [ ] 최근 검색어 저장 DB생성
- [ ] 검색 요청 시 DB에 해당 검색어 저장
- [ ] 최근 검색어 요창 시 DB에서 데이터 꺼내오기
